# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in refgraph.gemspec
gemspec

gem "rake", "~> 13.0"

gem "minitest", "~> 5.0"

gem "rake-compiler"

gem "jscall", "~> 1.4.0"

